### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by fingolfin**
This contains a bunch of cleanups and fixes for simpcomp.

I have some further suggestions, but since they are bigger, I leave them as comments only:
- You may want to convert the files in the repository from windows line ends (CR/LF) to the unix line ends, the native git format -- even if you are Windows users (in that case, you should set git to convert the line ends on the fly for you). Otherwise, e.g. `configure.ac` is not very useful...
- Perhaps consider removing generated files from the repository (such as `configure`, `Makefile.in`, `missing`, ...). Developers should just generate them on the fly.
- It would be nice if your repository was directly usable as a GAP package. But it isn't, because the `PackageInfo.g` does not contain a valid version number, and thus GAP prefers any older version laying around. If you change the version in there to e.g. "2.dev", it will work.

Thanks!

### CODE REVIEW

**Comment by simpcomp-team** [comment]
Hi,

This is a long overdue comment regarding the above cleanup.

Thanks for pointing out these issues. I carefully went over them and implemented most of them (rather than merging your commits - I wanted to properly follow all the changes and figured this would be the best way).

There are two issues remaining at present. 

1) Generated files. Of course, they should not be in the repository. 
2) The version number in PackageInfo.g. This is due to our deploy system and cannot trivially be fixed. We can probably work around the issue in PackageInfo.g and make the package usable from the repository, but there are other places in the package where adjustments need to be made as well.

We are currently discussing how to best resolve these problems.

Cheers
(Jonathan)

**Comment by fingolfin** [comment]
Well, I am glad to hear that. While you are ait, perhaps also update .gitignore, by adding these:
```
/Makefile
/autom4te.cache/
/bin/
/bistellar
/config.log
/config.status
/src/.deps/
/src/*.o
```

**Comment by fingolfin** [comment]
By the way, instead of throwing away all the commits in this PR, and manually applying parts of the changes in here, you could also have cherry-picked the relevant commits, like d1fb22b1e58f60e1f1b64a17520760c35290ab4c and ae2b7a8f4d3c716dce826142da6c0a41de453347

**Comment by simpcomp-team** [comment]
Just changed .gitignore. Thanks for pointing this out.

And thanks for the hint regarding the commits. Will do so in the future.

**Pull request closed without merging**
