### PR TITLE
CI: install grape to make tests pass

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Please don't merge it just now, I first want to see if it really fixes things

**Comment by fingolfin** [comment]
Excellent, with this the tests for master and stable-4.11 pass. Now will have a look at 4.10 and 4.9

**Comment by fingolfin** [comment]
With 4.9 and 4.10, we get this test failure. I can't judge whether it indicates an actual regression, is trivial, or something else:
```
########> Diff in tst/simpcomp.tst:377
# Input is:
SCSpanningTree(c);
# Expected output:
<SimplicialComplex: spanning tree of test | dim = 1 | n = 8>
# But found:
<SimplicialComplex: spanning tree of Bd(\beta^4) | dim = 1 | n = 8>
########
simpcomp package test
msecs: 10370
```

**Comment by simpcomp-team** [comment]
I think the manual built failed because there was an unresolved conflict in howto.xml.

I updated this a minute ago before I saw your message.

**Comment by fingolfin** [comment]
Yeah see also PR #38 :joy:

**Comment by fingolfin** [comment]
Anyway, feel free to merge this as-is. Regarding the 4.9/4.10 failures, I think "properly" addressing them requires domain knowledge about simpcomp I lack, so I can't help -- but of course you can also just decide to not care and stop testing with these versions of GAP (in that case, I would suggest to also increase the required GAP version in `PackageInfo.g` appropriately).

**Pull request merged**
